### Application version ###
applicationVersion=0.0.1-SNAPSHOT

### Project configs ###
projectGroup=io.plady.moimyeon

### Project dependency versions ###
kotlinVersion=2.3.21
javaVersion=25

### Plugin dependency versions ###
asciidoctorConvertVersion=4.0.5
ktlintVersion=14.2.0
restdocsApiSpecVersion=0.20.1

### Spring dependency versions ###
springBootVersion=4.1.0
springDependencyManagementVersion=1.1.7
springCloudDependenciesVersion=2025.1.2
springAiVersion=2.0.0

### External dependency versions ###
springMockkVersion=5.0.1
sentryVersion=8.43.2
awsSdkVersion=2.41.22
pdfBoxVersion=3.0.7
