spring.application.name: batch-app
spring.profiles.active: local

spring:
  config:
    import:
      - monitoring.yml
      - logging.yml
      - db-core.yml

---
spring.config.activate.on-profile: local


---
spring.config.activate.on-profile: local-dev


---
spring.config.activate.on-profile: dev


---
spring.config.activate.on-profile: staging


---
spring.config.activate.on-profile: live
