package io.plady.moimyeon.core.enums

enum class EventType {
    ROOM_APPLICATION_SUBMITTED,
    ROOM_APPLICATION_ACCEPTED,
    ROOM_APPLICATION_REJECTED,
    ROOM_CONFIRMED,
    ROOM_COMPLETED,
    ROOM_CANCELED,
    ROOM_HOST_DELEGATED,
    ROOM_RECRUITING_REOPENED,
    REVIEW_PUBLISHED,
    ROOM_COMMENT_POSTED,
}
